// Real responses captured from the deployed Veritarach service.
// Generated by calling POST /predict on each sample below, not written by hand.
// Captured 2026-08-18. Regenerate if the model is retrained.

export type DetectorSample = {
  id: string;
  /** What the text actually is. */
  truth: "human" | "ai";
  caption: string;
  text: string;
  /** Exactly what the model returned. */
  verdict: string;
  confidence: number;
  correct: boolean;
};

export const capturedOn = "2026-08-18";
/** Pre-formatted at generation time, so no locale work happens during hydration. */
export const capturedOnLabel = "18 August 2026";

export const detectorSamples: DetectorSample[] = [
  {
    id: "human-informal",
    truth: "human",
    caption: "A developer venting in a chat message",
    text: "honestly i spent like three hours on this bug and it turned out the config flag i was trusting didnt even control the thing it said it did. absolutely fuming. anyway fixed now, one line.",
    verdict: "human_written",
    confidence: 0.9999920129776001,
    correct: true,
  },
  {
    id: "human-reference",
    truth: "human",
    caption: "A reference-style paragraph, close to the Wikipedia text in training",
    text: "The Kinect was a motion sensing input device produced by Microsoft, first released in November 2010 for the Xbox 360. It used an infrared projector and camera to track movement in three dimensions.",
    verdict: "human_written",
    confidence: 0.9971175193786621,
    correct: true,
  },
  {
    id: "ai-technical",
    truth: "ai",
    caption: "A model explaining a technical fix",
    text: "To resolve this issue, you should first ensure that your dependencies are properly installed. It is important to note that version mismatches can often lead to unexpected behaviour. Additionally, consider leveraging a virtual environment to maintain isolation between your projects.",
    verdict: "ai_generated",
    confidence: 0.9998941421508789,
    correct: true,
  },
  {
    id: "ai-assistant",
    truth: "ai",
    caption: "A model in its most recognisable assistant voice",
    text: "Certainly! Here are several key considerations to keep in mind. First, it is important to note that maintaining a consistent schedule can significantly enhance productivity. Additionally, leveraging robust tools will ensure that your workflow remains seamless and efficient.",
    verdict: "human_written",
    confidence: 0.986056923866272,
    correct: false,
  },
  {
    id: "ai-essay",
    truth: "ai",
    caption: "A model writing in an academic register",
    text: "The proliferation of large language models has fundamentally transformed the landscape of natural language processing. These systems, trained on vast corpora of text, demonstrate remarkable capabilities across a diverse array of downstream tasks, thereby reshaping our understanding of machine intelligence.",
    verdict: "human_written",
    confidence: 0.9999843835830688,
    correct: false,
  },
  {
    id: "ai-explainer",
    truth: "ai",
    caption: "A model answering a question, the shape closest to its training data",
    text: "The sky appears blue due to a phenomenon known as Rayleigh scattering. When sunlight enters the Earth's atmosphere, it collides with gas molecules. Blue light has a shorter wavelength than red light, and is therefore scattered more strongly in all directions. This scattered blue light is what we observe when we look up at the sky during the day.",
    verdict: "human_written",
    confidence: 0.8530450463294983,
    correct: false,
  },
];
